
/* File generated by gen_cfile.py. Should not be modified. */

#include "CanARD.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER32 FrontSteering_MeasuredSpeed = 0x0;		/* Mapped at index 0x2210, subindex 0x01 */
UNS16 FrontSteering_Ds402State = 0x0;		/* Mapped at index 0x2210, subindex 0x02 */
INTEGER32 FrontSteering_MeasuredPosition = 0x0;		/* Mapped at index 0x2210, subindex 0x03 */
INTEGER16 FrontSteering_MeasuredCurrent = 0x0;		/* Mapped at index 0x2210, subindex 0x04 */
UNS32 FrontSteering_FaulhaberCommandParameter = 0x0;		/* Mapped at index 0x2210, subindex 0x05 */
UNS32 FrontSteering_FaulhaberCommand = 0x0;		/* Mapped at index 0x2210, subindex 0x06 */
UNS8 FrontSteering_FaulHaberCommandReturn = 0x0;		/* Mapped at index 0x2210, subindex 0x07 */
UNS8 FrontSteering_FaulHaberCommandReturnCode = 0x0;		/* Mapped at index 0x2210, subindex 0x08 */
UNS32 FrontSteering_FaulHaberCommandReturnParameter = 0x0;		/* Mapped at index 0x2210, subindex 0x09 */
INTEGER32 RightDriving_MeasuredSpeed = 0x0;		/* Mapped at index 0x2330, subindex 0x01 */
UNS16 RightDriving_Ds402State = 0x0;		/* Mapped at index 0x2330, subindex 0x02 */
INTEGER32 RightDriving_MeasuredPosition = 0x0;		/* Mapped at index 0x2330, subindex 0x03 */
INTEGER16 RightDriving_MeasuredCurrent = 0x0;		/* Mapped at index 0x2330, subindex 0x04 */
UNS32 RightDriving_FaulhaberCommandParameter = 0x0;		/* Mapped at index 0x2330, subindex 0x05 */
UNS8 RightDriving_FaulhaberCommand = 0x0;		/* Mapped at index 0x2330, subindex 0x06 */
UNS8 RightDriving_FaulHaberCommandReturn = 0x0;		/* Mapped at index 0x2330, subindex 0x07 */
UNS8 RightDriving_FaulHaberCommandReturnCode = 0x0;		/* Mapped at index 0x2330, subindex 0x08 */
UNS32 RightDriving_FaulHaberCommandReturnParameter = 0x0;		/* Mapped at index 0x2330, subindex 0x09 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CanARD_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CanARD_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CanARD_iam_a_slave = 0;

TIMER_HANDLE CanARD_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CanARD_obj1000 = 0x0;	/* 0 */
                    subindex CanARD_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CanARD_obj1001 = 0x0;	/* 0 */
                    subindex CanARD_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CanARD_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CanARD_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t CanARD_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 CanARD_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t CanARD_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CanARD_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 CanARD_obj1006 = 0x186A0;	/* 100000 */
                    ODCallback_t CanARD_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CanARD_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 CanARD_obj1014 = 0x80;	/* 128 */
                    subindex CanARD_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CanARD_highestSubIndex_obj1016 = 0;
                    UNS32 CanARD_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 CanARD_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 CanARD_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CanARD_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CanARD_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 CanARD_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex CanARD_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x621;	/* 1569 */
                    UNS32 CanARD_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x5A1;	/* 1441 */
                    UNS8 CanARD_obj1280_Node_ID_of_the_SDO_Server = 0x21;	/* 33 */
                    subindex CanARD_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1400_COB_ID_used_by_PDO = 0x1A1;	/* 417 */
                    UNS8 CanARD_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1401_COB_ID_used_by_PDO = 0x2A1;	/* 673 */
                    UNS8 CanARD_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1402_COB_ID_used_by_PDO = 0x3A1;	/* 929 */
                    UNS8 CanARD_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1402_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 CanARD_obj1600[] = 
                    {
                      0x22100210	/* 571474448 */
                    };
                    subindex CanARD_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1601[] = 
                    {
                      0x22100708,	/* 571475720 */
                      0x22100920,	/* 571476256 */
                      0x22100808	/* 571475976 */
                    };
                    subindex CanARD_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[2] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1602[] = 
                    {
                      0x22100320,	/* 571474720 */
                      0x22100410	/* 571474960 */
                    };
                    subindex CanARD_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1602[1] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1800_COB_ID_used_by_PDO = 0x321;	/* 801 */
                    UNS8 CanARD_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 CanARD_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CanARD_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1A00[] = 
                    {
                      0x22100620,	/* 571475488 */
                      0x22100520	/* 571475232 */
                    };
                    subindex CanARD_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A00[1] }
                     };

/* index 0x2210 :   Mapped variable FrontSteering */
                    UNS8 CanARD_highestSubIndex_obj2210 = 9; /* number of subindex - 1*/
                    ODCallback_t FrontSteering_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index2210[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2210 },
                       { RW, int32, sizeof (INTEGER32), (void*)&FrontSteering_MeasuredSpeed },
                       { RW, uint16, sizeof (UNS16), (void*)&FrontSteering_Ds402State },
                       { RW, int32, sizeof (INTEGER32), (void*)&FrontSteering_MeasuredPosition },
                       { RW, int16, sizeof (INTEGER16), (void*)&FrontSteering_MeasuredCurrent },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulhaberCommandParameter },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulhaberCommand },
                       { RW, uint8, sizeof (UNS8), (void*)&FrontSteering_FaulHaberCommandReturn },
                       { RW, uint8, sizeof (UNS8), (void*)&FrontSteering_FaulHaberCommandReturnCode },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulHaberCommandReturnParameter }
                     };

/* index 0x2330 :   Mapped variable RightDriving */
                    UNS8 CanARD_highestSubIndex_obj2330 = 9; /* number of subindex - 1*/
                    ODCallback_t RightDriving_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index2330[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2330 },
                       { RW, int32, sizeof (INTEGER32), (void*)&RightDriving_MeasuredSpeed },
                       { RW, uint16, sizeof (UNS16), (void*)&RightDriving_Ds402State },
                       { RW, int32, sizeof (INTEGER32), (void*)&RightDriving_MeasuredPosition },
                       { RW, int16, sizeof (INTEGER16), (void*)&RightDriving_MeasuredCurrent },
                       { RW, uint32, sizeof (UNS32), (void*)&RightDriving_FaulhaberCommandParameter },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulhaberCommand },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulHaberCommandReturn },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulHaberCommandReturnCode },
                       { RW, uint32, sizeof (UNS32), (void*)&RightDriving_FaulHaberCommandReturnParameter }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CanARD_objdict[] = 
{
  { (subindex*)CanARD_Index1000,sizeof(CanARD_Index1000)/sizeof(CanARD_Index1000[0]), 0x1000},
  { (subindex*)CanARD_Index1001,sizeof(CanARD_Index1001)/sizeof(CanARD_Index1001[0]), 0x1001},
  { (subindex*)CanARD_Index1005,sizeof(CanARD_Index1005)/sizeof(CanARD_Index1005[0]), 0x1005},
  { (subindex*)CanARD_Index1006,sizeof(CanARD_Index1006)/sizeof(CanARD_Index1006[0]), 0x1006},
  { (subindex*)CanARD_Index1014,sizeof(CanARD_Index1014)/sizeof(CanARD_Index1014[0]), 0x1014},
  { (subindex*)CanARD_Index1018,sizeof(CanARD_Index1018)/sizeof(CanARD_Index1018[0]), 0x1018},
  { (subindex*)CanARD_Index1200,sizeof(CanARD_Index1200)/sizeof(CanARD_Index1200[0]), 0x1200},
  { (subindex*)CanARD_Index1280,sizeof(CanARD_Index1280)/sizeof(CanARD_Index1280[0]), 0x1280},
  { (subindex*)CanARD_Index1400,sizeof(CanARD_Index1400)/sizeof(CanARD_Index1400[0]), 0x1400},
  { (subindex*)CanARD_Index1401,sizeof(CanARD_Index1401)/sizeof(CanARD_Index1401[0]), 0x1401},
  { (subindex*)CanARD_Index1402,sizeof(CanARD_Index1402)/sizeof(CanARD_Index1402[0]), 0x1402},
  { (subindex*)CanARD_Index1600,sizeof(CanARD_Index1600)/sizeof(CanARD_Index1600[0]), 0x1600},
  { (subindex*)CanARD_Index1601,sizeof(CanARD_Index1601)/sizeof(CanARD_Index1601[0]), 0x1601},
  { (subindex*)CanARD_Index1602,sizeof(CanARD_Index1602)/sizeof(CanARD_Index1602[0]), 0x1602},
  { (subindex*)CanARD_Index1800,sizeof(CanARD_Index1800)/sizeof(CanARD_Index1800[0]), 0x1800},
  { (subindex*)CanARD_Index1A00,sizeof(CanARD_Index1A00)/sizeof(CanARD_Index1A00[0]), 0x1A00},
  { (subindex*)CanARD_Index2210,sizeof(CanARD_Index2210)/sizeof(CanARD_Index2210[0]), 0x2210},
  { (subindex*)CanARD_Index2330,sizeof(CanARD_Index2330)/sizeof(CanARD_Index2330[0]), 0x2330},
};

const indextable * CanARD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = CanARD_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = CanARD_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1401: i = 9;break;
		case 0x1402: i = 10;break;
		case 0x1600: i = 11;break;
		case 0x1601: i = 12;break;
		case 0x1602: i = 13;break;
		case 0x1800: i = 14;*callbacks = CanARD_Index1800_callbacks; break;
		case 0x1A00: i = 15;break;
		case 0x2210: i = 16;*callbacks = FrontSteering_callbacks; break;
		case 0x2330: i = 17;*callbacks = RightDriving_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CanARD_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CanARD_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index CanARD_firstIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  8, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const quick_index CanARD_lastIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  10, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const UNS16 CanARD_ObjdictSize = sizeof(CanARD_objdict)/sizeof(CanARD_objdict[0]); 

CO_Data CanARD_Data = CANOPEN_NODE_DATA_INITIALIZER(CanARD);

