
/* File generated by gen_cfile.py. Should not be modified. */

#include "CanARD.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Woodhead_outputs = 0x0;		/* Mapped at index 0x2050, subindex 0x01 */
INTEGER32 FrontSteering_MeasuredSpeed = 0x0;		/* Mapped at index 0x2210, subindex 0x01 */
UNS16 FrontSteering_Ds402State = 0x0;		/* Mapped at index 0x2210, subindex 0x02 */
INTEGER32 FrontSteering_MeasuredPosition = 0x0;		/* Mapped at index 0x2210, subindex 0x03 */
INTEGER16 FrontSteering_MeasuredCurrent = 0x0;		/* Mapped at index 0x2210, subindex 0x04 */
UNS32 FrontSteering_FaulhaberCommandParameter = 0x0;		/* Mapped at index 0x2210, subindex 0x05 */
UNS32 FrontSteering_FaulhaberCommand = 0x0;		/* Mapped at index 0x2210, subindex 0x06 */
UNS8 FrontSteering_FaulhaberCommandReturn = 0x0;		/* Mapped at index 0x2210, subindex 0x07 */
UNS8 FrontSteering_FaulhaberCommandReturnCode = 0x0;		/* Mapped at index 0x2210, subindex 0x08 */
UNS32 FrontSteering_FaulhaberCommandReturnParameter = 0x0;		/* Mapped at index 0x2210, subindex 0x09 */
INTEGER32 LeftDriving_MeasuredSpeed = 0x0;		/* Mapped at index 0x2320, subindex 0x01 */
UNS16 LeftDriving_Ds402State = 0x0;		/* Mapped at index 0x2320, subindex 0x02 */
INTEGER32 LeftDriving_MeasuredPosition = 0x0;		/* Mapped at index 0x2320, subindex 0x03 */
INTEGER16 LeftDriving_MeasuredCurrent = 0x0;		/* Mapped at index 0x2320, subindex 0x04 */
UNS32 LeftDriving_FaulhaberCommandParameter = 0x0;		/* Mapped at index 0x2320, subindex 0x05 */
UNS8 LeftDriving_FaulhaberCommand = 0x0;		/* Mapped at index 0x2320, subindex 0x06 */
UNS8 LeftDriving_FaulhaberCommandReturn = 0x0;		/* Mapped at index 0x2320, subindex 0x07 */
UNS8 LeftDriving_FaulhaberCommandReturnCode = 0x0;		/* Mapped at index 0x2320, subindex 0x08 */
UNS32 LeftDriving_FaulhaberCommandReturnParameter = 0x0;		/* Mapped at index 0x2320, subindex 0x09 */
UNS8 LeftDriving_Undefined = 0x0;		/* Mapped at index 0x2320, subindex 0x0A */
INTEGER32 RightDriving_MeasuredSpeed = 0x0;		/* Mapped at index 0x2330, subindex 0x01 */
UNS16 RightDriving_Ds402State = 0x0;		/* Mapped at index 0x2330, subindex 0x02 */
INTEGER32 RightDriving_MeasuredPosition = 0x0;		/* Mapped at index 0x2330, subindex 0x03 */
INTEGER16 RightDriving_MeasuredCurrent = 0x0;		/* Mapped at index 0x2330, subindex 0x04 */
UNS32 RightDriving_FaulhaberCommandParameter = 0x0;		/* Mapped at index 0x2330, subindex 0x05 */
UNS8 RightDriving_FaulhaberCommand = 0x0;		/* Mapped at index 0x2330, subindex 0x06 */
UNS8 RightDriving_FaulhaberCommandReturn = 0x0;		/* Mapped at index 0x2330, subindex 0x07 */
UNS8 RightDriving_FaulhaberCommandReturnCode = 0x0;		/* Mapped at index 0x2330, subindex 0x08 */
UNS32 RightDriving_FaulhaberCommandReturnParameter = 0x0;		/* Mapped at index 0x2330, subindex 0x09 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CanARD_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CanARD_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CanARD_iam_a_slave = 0;

TIMER_HANDLE CanARD_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CanARD_obj1000 = 0x0;	/* 0 */
                    subindex CanARD_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CanARD_obj1001 = 0x0;	/* 0 */
                    subindex CanARD_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CanARD_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CanARD_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t CanARD_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 CanARD_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t CanARD_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CanARD_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 CanARD_obj1006 = 0xC350;	/* 50000 */
                    ODCallback_t CanARD_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex CanARD_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 CanARD_obj1014 = 0x80;	/* 128 */
                    subindex CanARD_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CanARD_highestSubIndex_obj1016 = 0;
                    UNS32 CanARD_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 CanARD_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 CanARD_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CanARD_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CanARD_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CanARD_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 CanARD_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex CanARD_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&CanARD_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x621;	/* 1569 */
                    UNS32 CanARD_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x5A1;	/* 1441 */
                    UNS8 CanARD_obj1280_Node_ID_of_the_SDO_Server = 0x21;	/* 33 */
                    subindex CanARD_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x632;	/* 1586 */
                    UNS32 CanARD_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x5B2;	/* 1458 */
                    UNS8 CanARD_obj1281_Node_ID_of_the_SDO_Server = 0x32;	/* 50 */
                    subindex CanARD_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x633;	/* 1587 */
                    UNS32 CanARD_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x5B3;	/* 1459 */
                    UNS8 CanARD_obj1282_Node_ID_of_the_SDO_Server = 0x33;	/* 51 */
                    subindex CanARD_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 CanARD_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 CanARD_obj1283_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex CanARD_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1400_COB_ID_used_by_PDO = 0x1A1;	/* 417 */
                    UNS8 CanARD_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1401_COB_ID_used_by_PDO = 0x2A1;	/* 673 */
                    UNS8 CanARD_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1402_COB_ID_used_by_PDO = 0x3A1;	/* 929 */
                    UNS8 CanARD_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1402_Event_Timer }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1403_COB_ID_used_by_PDO = 0x1B2;	/* 434 */
                    UNS8 CanARD_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1403_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1403_Event_Timer }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1404 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1404_COB_ID_used_by_PDO = 0x2B2;	/* 690 */
                    UNS8 CanARD_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1404_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1404_Event_Timer }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1405 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1405_COB_ID_used_by_PDO = 0x3B2;	/* 946 */
                    UNS8 CanARD_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1405_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1405_Event_Timer }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1406 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1406_COB_ID_used_by_PDO = 0x1B3;	/* 435 */
                    UNS8 CanARD_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1406_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1406_Event_Timer }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1407 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1407_COB_ID_used_by_PDO = 0x2B3;	/* 691 */
                    UNS8 CanARD_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1407_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1407_Event_Timer }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1408 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1408_COB_ID_used_by_PDO = 0x3B3;	/* 947 */
                    UNS8 CanARD_obj1408_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1408_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1408_Event_Timer }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1409 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1409_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 CanARD_obj1409_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CanARD_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1409_Event_Timer = 0x0;	/* 0 */
                    subindex CanARD_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1409_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 CanARD_obj1600[] = 
                    {
                      0x22100210	/* 571474448 */
                    };
                    subindex CanARD_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1601[] = 
                    {
                      0x22100708,	/* 571475720 */
                      0x22100920,	/* 571476256 */
                      0x22100808	/* 571475976 */
                    };
                    subindex CanARD_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1601[2] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1602[] = 
                    {
                      0x22100320,	/* 571474720 */
                      0x22100410	/* 571474960 */
                    };
                    subindex CanARD_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1602[1] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 CanARD_obj1603[] = 
                    {
                      0x23200210	/* 589300240 */
                    };
                    subindex CanARD_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1604 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1604[] = 
                    {
                      0x23200708,	/* 589301512 */
                      0x23200920,	/* 589302048 */
                      0x23200808	/* 589301768 */
                    };
                    subindex CanARD_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1604[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1604[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1604[2] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1605 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1605[] = 
                    {
                      0x23200320,	/* 589300512 */
                      0x23200410	/* 589300752 */
                    };
                    subindex CanARD_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1605[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1605[1] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1606 = 1; /* number of subindex - 1*/
                    UNS32 CanARD_obj1606[] = 
                    {
                      0x23300210	/* 590348816 */
                    };
                    subindex CanARD_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1606[0] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1607 = 3; /* number of subindex - 1*/
                    UNS32 CanARD_obj1607[] = 
                    {
                      0x23300708,	/* 590350088 */
                      0x23300920,	/* 590350624 */
                      0x23300808	/* 590350344 */
                    };
                    subindex CanARD_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1607[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1607[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1607[2] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1608 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1608[] = 
                    {
                      0x23300320,	/* 590349088 */
                      0x23300410	/* 590349328 */
                    };
                    subindex CanARD_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1608[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1608[1] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1609 = 1; /* number of subindex - 1*/
                    UNS32 CanARD_obj1609[] = 
                    {
                      0x20500108	/* 542114056 */
                    };
                    subindex CanARD_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1609[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1800_COB_ID_used_by_PDO = 0x321;	/* 801 */
                    UNS8 CanARD_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 CanARD_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CanARD_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1801_COB_ID_used_by_PDO = 0x332;	/* 818 */
                    UNS8 CanARD_obj1801_Transmission_Type = 0x1;	/* 1 */
                    UNS16 CanARD_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CanARD_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1801_Event_Timer }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 CanARD_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 CanARD_obj1802_COB_ID_used_by_PDO = 0x333;	/* 819 */
                    UNS8 CanARD_obj1802_Transmission_Type = 0x1;	/* 1 */
                    UNS16 CanARD_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CanARD_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CanARD_obj1802_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CanARD_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CanARD_obj1802_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1A00[] = 
                    {
                      0x22100620,	/* 571475488 */
                      0x22100520	/* 571475232 */
                    };
                    subindex CanARD_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1A01[] = 
                    {
                      0x23200608,	/* 589301256 */
                      0x23200520	/* 589301024 */
                    };
                    subindex CanARD_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 CanARD_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 CanARD_obj1A02[] = 
                    {
                      0x23300608,	/* 590349832 */
                      0x23300520	/* 590349600 */
                    };
                    subindex CanARD_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CanARD_obj1A02[1] }
                     };

/* index 0x2050 :   Mapped variable Woodhead */
                    UNS8 CanARD_highestSubIndex_obj2050 = 1; /* number of subindex - 1*/
                    subindex CanARD_Index2050[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2050 },
                       { RW, uint8, sizeof (UNS8), (void*)&Woodhead_outputs }
                     };

/* index 0x2210 :   Mapped variable FrontSteering */
                    UNS8 CanARD_highestSubIndex_obj2210 = 9; /* number of subindex - 1*/
                    ODCallback_t FrontSteering_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index2210[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2210 },
                       { RW, int32, sizeof (INTEGER32), (void*)&FrontSteering_MeasuredSpeed },
                       { RW, uint16, sizeof (UNS16), (void*)&FrontSteering_Ds402State },
                       { RW, int32, sizeof (INTEGER32), (void*)&FrontSteering_MeasuredPosition },
                       { RW, int16, sizeof (INTEGER16), (void*)&FrontSteering_MeasuredCurrent },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulhaberCommandParameter },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulhaberCommand },
                       { RW, uint8, sizeof (UNS8), (void*)&FrontSteering_FaulhaberCommandReturn },
                       { RW, uint8, sizeof (UNS8), (void*)&FrontSteering_FaulhaberCommandReturnCode },
                       { RW, uint32, sizeof (UNS32), (void*)&FrontSteering_FaulhaberCommandReturnParameter }
                     };

/* index 0x2320 :   Mapped variable LeftDriving */
                    UNS8 CanARD_highestSubIndex_obj2320 = 10; /* number of subindex - 1*/
                    ODCallback_t LeftDriving_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index2320[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2320 },
                       { RW, int32, sizeof (INTEGER32), (void*)&LeftDriving_MeasuredSpeed },
                       { RW, uint16, sizeof (UNS16), (void*)&LeftDriving_Ds402State },
                       { RW, int32, sizeof (INTEGER32), (void*)&LeftDriving_MeasuredPosition },
                       { RW, int16, sizeof (INTEGER16), (void*)&LeftDriving_MeasuredCurrent },
                       { RW, uint32, sizeof (UNS32), (void*)&LeftDriving_FaulhaberCommandParameter },
                       { RW, uint8, sizeof (UNS8), (void*)&LeftDriving_FaulhaberCommand },
                       { RW, uint8, sizeof (UNS8), (void*)&LeftDriving_FaulhaberCommandReturn },
                       { RW, uint8, sizeof (UNS8), (void*)&LeftDriving_FaulhaberCommandReturnCode },
                       { RW, uint32, sizeof (UNS32), (void*)&LeftDriving_FaulhaberCommandReturnParameter },
                       { RW, uint8, sizeof (UNS8), (void*)&LeftDriving_Undefined }
                     };

/* index 0x2330 :   Mapped variable RightDriving */
                    UNS8 CanARD_highestSubIndex_obj2330 = 9; /* number of subindex - 1*/
                    ODCallback_t RightDriving_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CanARD_Index2330[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CanARD_highestSubIndex_obj2330 },
                       { RW, int32, sizeof (INTEGER32), (void*)&RightDriving_MeasuredSpeed },
                       { RW, uint16, sizeof (UNS16), (void*)&RightDriving_Ds402State },
                       { RW, int32, sizeof (INTEGER32), (void*)&RightDriving_MeasuredPosition },
                       { RW, int16, sizeof (INTEGER16), (void*)&RightDriving_MeasuredCurrent },
                       { RW, uint32, sizeof (UNS32), (void*)&RightDriving_FaulhaberCommandParameter },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulhaberCommand },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulhaberCommandReturn },
                       { RW, uint8, sizeof (UNS8), (void*)&RightDriving_FaulhaberCommandReturnCode },
                       { RW, uint32, sizeof (UNS32), (void*)&RightDriving_FaulhaberCommandReturnParameter }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CanARD_objdict[] = 
{
  { (subindex*)CanARD_Index1000,sizeof(CanARD_Index1000)/sizeof(CanARD_Index1000[0]), 0x1000},
  { (subindex*)CanARD_Index1001,sizeof(CanARD_Index1001)/sizeof(CanARD_Index1001[0]), 0x1001},
  { (subindex*)CanARD_Index1005,sizeof(CanARD_Index1005)/sizeof(CanARD_Index1005[0]), 0x1005},
  { (subindex*)CanARD_Index1006,sizeof(CanARD_Index1006)/sizeof(CanARD_Index1006[0]), 0x1006},
  { (subindex*)CanARD_Index1014,sizeof(CanARD_Index1014)/sizeof(CanARD_Index1014[0]), 0x1014},
  { (subindex*)CanARD_Index1018,sizeof(CanARD_Index1018)/sizeof(CanARD_Index1018[0]), 0x1018},
  { (subindex*)CanARD_Index1200,sizeof(CanARD_Index1200)/sizeof(CanARD_Index1200[0]), 0x1200},
  { (subindex*)CanARD_Index1280,sizeof(CanARD_Index1280)/sizeof(CanARD_Index1280[0]), 0x1280},
  { (subindex*)CanARD_Index1281,sizeof(CanARD_Index1281)/sizeof(CanARD_Index1281[0]), 0x1281},
  { (subindex*)CanARD_Index1282,sizeof(CanARD_Index1282)/sizeof(CanARD_Index1282[0]), 0x1282},
  { (subindex*)CanARD_Index1283,sizeof(CanARD_Index1283)/sizeof(CanARD_Index1283[0]), 0x1283},
  { (subindex*)CanARD_Index1400,sizeof(CanARD_Index1400)/sizeof(CanARD_Index1400[0]), 0x1400},
  { (subindex*)CanARD_Index1401,sizeof(CanARD_Index1401)/sizeof(CanARD_Index1401[0]), 0x1401},
  { (subindex*)CanARD_Index1402,sizeof(CanARD_Index1402)/sizeof(CanARD_Index1402[0]), 0x1402},
  { (subindex*)CanARD_Index1403,sizeof(CanARD_Index1403)/sizeof(CanARD_Index1403[0]), 0x1403},
  { (subindex*)CanARD_Index1404,sizeof(CanARD_Index1404)/sizeof(CanARD_Index1404[0]), 0x1404},
  { (subindex*)CanARD_Index1405,sizeof(CanARD_Index1405)/sizeof(CanARD_Index1405[0]), 0x1405},
  { (subindex*)CanARD_Index1406,sizeof(CanARD_Index1406)/sizeof(CanARD_Index1406[0]), 0x1406},
  { (subindex*)CanARD_Index1407,sizeof(CanARD_Index1407)/sizeof(CanARD_Index1407[0]), 0x1407},
  { (subindex*)CanARD_Index1408,sizeof(CanARD_Index1408)/sizeof(CanARD_Index1408[0]), 0x1408},
  { (subindex*)CanARD_Index1409,sizeof(CanARD_Index1409)/sizeof(CanARD_Index1409[0]), 0x1409},
  { (subindex*)CanARD_Index1600,sizeof(CanARD_Index1600)/sizeof(CanARD_Index1600[0]), 0x1600},
  { (subindex*)CanARD_Index1601,sizeof(CanARD_Index1601)/sizeof(CanARD_Index1601[0]), 0x1601},
  { (subindex*)CanARD_Index1602,sizeof(CanARD_Index1602)/sizeof(CanARD_Index1602[0]), 0x1602},
  { (subindex*)CanARD_Index1603,sizeof(CanARD_Index1603)/sizeof(CanARD_Index1603[0]), 0x1603},
  { (subindex*)CanARD_Index1604,sizeof(CanARD_Index1604)/sizeof(CanARD_Index1604[0]), 0x1604},
  { (subindex*)CanARD_Index1605,sizeof(CanARD_Index1605)/sizeof(CanARD_Index1605[0]), 0x1605},
  { (subindex*)CanARD_Index1606,sizeof(CanARD_Index1606)/sizeof(CanARD_Index1606[0]), 0x1606},
  { (subindex*)CanARD_Index1607,sizeof(CanARD_Index1607)/sizeof(CanARD_Index1607[0]), 0x1607},
  { (subindex*)CanARD_Index1608,sizeof(CanARD_Index1608)/sizeof(CanARD_Index1608[0]), 0x1608},
  { (subindex*)CanARD_Index1609,sizeof(CanARD_Index1609)/sizeof(CanARD_Index1609[0]), 0x1609},
  { (subindex*)CanARD_Index1800,sizeof(CanARD_Index1800)/sizeof(CanARD_Index1800[0]), 0x1800},
  { (subindex*)CanARD_Index1801,sizeof(CanARD_Index1801)/sizeof(CanARD_Index1801[0]), 0x1801},
  { (subindex*)CanARD_Index1802,sizeof(CanARD_Index1802)/sizeof(CanARD_Index1802[0]), 0x1802},
  { (subindex*)CanARD_Index1A00,sizeof(CanARD_Index1A00)/sizeof(CanARD_Index1A00[0]), 0x1A00},
  { (subindex*)CanARD_Index1A01,sizeof(CanARD_Index1A01)/sizeof(CanARD_Index1A01[0]), 0x1A01},
  { (subindex*)CanARD_Index1A02,sizeof(CanARD_Index1A02)/sizeof(CanARD_Index1A02[0]), 0x1A02},
  { (subindex*)CanARD_Index2050,sizeof(CanARD_Index2050)/sizeof(CanARD_Index2050[0]), 0x2050},
  { (subindex*)CanARD_Index2210,sizeof(CanARD_Index2210)/sizeof(CanARD_Index2210[0]), 0x2210},
  { (subindex*)CanARD_Index2320,sizeof(CanARD_Index2320)/sizeof(CanARD_Index2320[0]), 0x2320},
  { (subindex*)CanARD_Index2330,sizeof(CanARD_Index2330)/sizeof(CanARD_Index2330[0]), 0x2330},
};

const indextable * CanARD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = CanARD_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = CanARD_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1281: i = 8;break;
		case 0x1282: i = 9;break;
		case 0x1283: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1404: i = 15;break;
		case 0x1405: i = 16;break;
		case 0x1406: i = 17;break;
		case 0x1407: i = 18;break;
		case 0x1408: i = 19;break;
		case 0x1409: i = 20;break;
		case 0x1600: i = 21;break;
		case 0x1601: i = 22;break;
		case 0x1602: i = 23;break;
		case 0x1603: i = 24;break;
		case 0x1604: i = 25;break;
		case 0x1605: i = 26;break;
		case 0x1606: i = 27;break;
		case 0x1607: i = 28;break;
		case 0x1608: i = 29;break;
		case 0x1609: i = 30;break;
		case 0x1800: i = 31;*callbacks = CanARD_Index1800_callbacks; break;
		case 0x1801: i = 32;*callbacks = CanARD_Index1801_callbacks; break;
		case 0x1802: i = 33;*callbacks = CanARD_Index1802_callbacks; break;
		case 0x1A00: i = 34;break;
		case 0x1A01: i = 35;break;
		case 0x1A02: i = 36;break;
		case 0x2050: i = 37;break;
		case 0x2210: i = 38;*callbacks = FrontSteering_callbacks; break;
		case 0x2320: i = 39;*callbacks = LeftDriving_callbacks; break;
		case 0x2330: i = 40;*callbacks = RightDriving_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CanARD_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CanARD_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index CanARD_firstIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  11, /* PDO_RCV */
  21, /* PDO_RCV_MAP */
  31, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const quick_index CanARD_lastIndex = {
  6, /* SDO_SVR */
  10, /* SDO_CLT */
  20, /* PDO_RCV */
  30, /* PDO_RCV_MAP */
  33, /* PDO_TRS */
  36 /* PDO_TRS_MAP */
};

const UNS16 CanARD_ObjdictSize = sizeof(CanARD_objdict)/sizeof(CanARD_objdict[0]); 

CO_Data CanARD_Data = CANOPEN_NODE_DATA_INITIALIZER(CanARD);

