#!/bin/bash

WORKQUEUE=workqueue_queue_work,workqueue_activate_work,workqueue_execute_start,workqueue_execute_end
TIMER=timer_init,timer_start,timer_expire_entry,timer_expire_exit,timer_cancel
HRTIMER=hrtimer_init,hrtimer_start,hrtimer_expire_entry,hrtimer_expire_exit,hrtimer_cancel
ITIMER=itimer_state,itimer_expire
LTTNG=lttng_statedump_start,lttng_statedump_end,lttng_statedump_process_state,lttng_statedump_file_descriptor,lttng_statedump_vm_map,lttng_statedump_network_interface,lttng_statedump_interrupt
SKB=skb_kfree,skb_consume,skb_copy_datagram_iovec
SIGNAL=signal_generate,signal_deliver,signal_overflow_fail,signal_lose_info
SCSI=scsi_dispatch_cmd_start,scsi_dispatch_cmd_error,scsi_dispatch_cmd_done,scsi_dispatch_cmd_timeout,scsi_eh_wakeup
SCHEDULING=sched_kthread_stop,sched_kthread_stop_ret,sched_wakeup,sched_wakeup_new,sched_switch,sched_migrate_task,sched_process_free,sched_process_exit,sched_wait_task,sched_process_wait,sched_process_fork,sched_stat_wait,sched_stat_sleep,sched_stat_iowait,sched_stat_runtime,sched_pi_setprio
POWER=power_cpu_idle,power_cpu_frequency,power_machine_suspend,power_start,power_frequency,power_end,power_clock_enable,power_clock_disable,power_clock_set_rate,power_domain_target
IRQ=irq_handler_entry,irq_handler_exit,softirq_entry,softirq_exit,softirq_raise

lttng enable-event sched_switch,$IRQ -k