
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlaveB.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 SlaveBMap1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestSlaveB_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestSlaveB_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestSlaveB_iam_a_slave = 1;

TIMER_HANDLE TestSlaveB_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestSlaveB_obj1000 = 0x12D;	/* 301 */
                    subindex TestSlaveB_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestSlaveB_obj1001 = 0x0;	/* 0 */
                    subindex TestSlaveB_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 TestSlaveB_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t TestSlaveB_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlaveB_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[4] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[5] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[6] },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1003[7] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestSlaveB_obj1005 = 0x80;	/* 128 */
                    ODCallback_t TestSlaveB_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlaveB_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestSlaveB_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestSlaveB_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlaveB_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1006 }
                     };

/* index 0x1010 :   Store parameters. */
                    UNS8 TestSlaveB_highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    ODCallback_t TestSlaveB_Index1010_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlaveB_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1010_Save_Application_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1010_Save_Manufacturer_Parameters_1 }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 TestSlaveB_highestSubIndex_obj1011 = 4; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestSlaveB_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x0;	/* 0 */
                    ODCallback_t TestSlaveB_Index1011_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlaveB_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestSlaveB_obj1014 = 0x80;	/* 128 */
                    subindex TestSlaveB_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestSlaveB_highestSubIndex_obj1016 = 0;
                    UNS32 TestSlaveB_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestSlaveB_obj1017 = 0x0;	/* 0 */
                    ODCallback_t TestSlaveB_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlaveB_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlaveB_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestSlaveB_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1018_Vendor_ID = 0x12345679;	/* 305419897 */
                    UNS32 TestSlaveB_obj1018_Product_Code = 0x90123456;	/* 2417112150 */
                    UNS32 TestSlaveB_obj1018_Revision_Number = 0x78901234;	/* 2022707764 */
                    UNS32 TestSlaveB_obj1018_Serial_Number = 0x56789012;	/* 1450741778 */
                    subindex TestSlaveB_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestSlaveB_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TestSlaveB_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TestSlaveB_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestSlaveB_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TestSlaveB_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlaveB_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlaveB_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlaveB_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlaveB_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlaveB_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1800_COB_ID_used_by_PDO },
                       { RW|TO_BE_SAVE, uint8, sizeof (UNS8), (void*)&TestSlaveB_obj1800_Transmission_Type },
                       { RW|TO_BE_SAVE, uint16, sizeof (UNS16), (void*)&TestSlaveB_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlaveB_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlaveB_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestSlaveB_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 TestSlaveB_obj1A00[] = 
                    {
                      0x20000010	/* 536870928 */
                    };
                    subindex TestSlaveB_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlaveB_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlaveB_obj1A00[0] }
                     };

/* index 0x2000 :   Mapped variable SlaveBMap1 */
                    subindex TestSlaveB_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveBMap1 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestSlaveB_objdict[] = 
{
  { (subindex*)TestSlaveB_Index1000,sizeof(TestSlaveB_Index1000)/sizeof(TestSlaveB_Index1000[0]), 0x1000},
  { (subindex*)TestSlaveB_Index1001,sizeof(TestSlaveB_Index1001)/sizeof(TestSlaveB_Index1001[0]), 0x1001},
  { (subindex*)TestSlaveB_Index1003,sizeof(TestSlaveB_Index1003)/sizeof(TestSlaveB_Index1003[0]), 0x1003},
  { (subindex*)TestSlaveB_Index1005,sizeof(TestSlaveB_Index1005)/sizeof(TestSlaveB_Index1005[0]), 0x1005},
  { (subindex*)TestSlaveB_Index1006,sizeof(TestSlaveB_Index1006)/sizeof(TestSlaveB_Index1006[0]), 0x1006},
  { (subindex*)TestSlaveB_Index1010,sizeof(TestSlaveB_Index1010)/sizeof(TestSlaveB_Index1010[0]), 0x1010},
  { (subindex*)TestSlaveB_Index1011,sizeof(TestSlaveB_Index1011)/sizeof(TestSlaveB_Index1011[0]), 0x1011},
  { (subindex*)TestSlaveB_Index1014,sizeof(TestSlaveB_Index1014)/sizeof(TestSlaveB_Index1014[0]), 0x1014},
  { (subindex*)TestSlaveB_Index1017,sizeof(TestSlaveB_Index1017)/sizeof(TestSlaveB_Index1017[0]), 0x1017},
  { (subindex*)TestSlaveB_Index1018,sizeof(TestSlaveB_Index1018)/sizeof(TestSlaveB_Index1018[0]), 0x1018},
  { (subindex*)TestSlaveB_Index1200,sizeof(TestSlaveB_Index1200)/sizeof(TestSlaveB_Index1200[0]), 0x1200},
  { (subindex*)TestSlaveB_Index1800,sizeof(TestSlaveB_Index1800)/sizeof(TestSlaveB_Index1800[0]), 0x1800},
  { (subindex*)TestSlaveB_Index1A00,sizeof(TestSlaveB_Index1A00)/sizeof(TestSlaveB_Index1A00[0]), 0x1A00},
  { (subindex*)TestSlaveB_Index2000,sizeof(TestSlaveB_Index2000)/sizeof(TestSlaveB_Index2000[0]), 0x2000},
};

const indextable * TestSlaveB_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = TestSlaveB_Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = TestSlaveB_Index1005_callbacks; break;
		case 0x1006: i = 4;*callbacks = TestSlaveB_Index1006_callbacks; break;
		case 0x1010: i = 5;*callbacks = TestSlaveB_Index1010_callbacks; break;
		case 0x1011: i = 6;*callbacks = TestSlaveB_Index1011_callbacks; break;
		case 0x1014: i = 7;break;
		case 0x1017: i = 8;*callbacks = TestSlaveB_Index1017_callbacks; break;
		case 0x1018: i = 9;break;
		case 0x1200: i = 10;break;
		case 0x1800: i = 11;*callbacks = TestSlaveB_Index1800_callbacks; break;
		case 0x1A00: i = 12;break;
		case 0x2000: i = 13;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestSlaveB_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestSlaveB_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index TestSlaveB_firstIndex = {
  10, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  11, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

const quick_index TestSlaveB_lastIndex = {
  10, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  11, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

const UNS16 TestSlaveB_ObjdictSize = sizeof(TestSlaveB_objdict)/sizeof(TestSlaveB_objdict[0]); 

CO_Data TestSlaveB_Data = CANOPEN_NODE_DATA_INITIALIZER(TestSlaveB);

