
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVEB_H
#define TESTSLAVEB_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlaveB_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlaveB_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlaveB_Data;
extern UNS16 SlaveBMap1;		/* Mapped at index 0x2000, subindex 0x00*/

#endif // TESTSLAVEB_H
