/* Auto-generated by genmsg_cpp for file /opt/ard/arp_core/msg/OmniCommand.msg */
#ifndef ARP_CORE_BOOST_SERIALIZATION_OMNICOMMAND_H
#define ARP_CORE_BOOST_SERIALIZATION_OMNICOMMAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_core/OmniCommand.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_core::OmniCommand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("v_left_driving",m.v_left_driving);
    a & make_nvp("v_right_driving",m.v_right_driving);
    a & make_nvp("v_rear_driving",m.v_rear_driving);
    a & make_nvp("p_left_steering",m.p_left_steering);
    a & make_nvp("p_right_steering",m.p_right_steering);
    a & make_nvp("p_rear_steering",m.p_rear_steering);
}

} // namespace serialization
} // namespace boost

#endif // ARP_CORE_BOOST_SERIALIZATION_OMNICOMMAND_H

