"""autogenerated by genmsg_py from CannonState.msg. Do not edit."""
import roslib.message
import struct


class CannonState(roslib.message.Message):
  _md5sum = "1541711f710415e27514d48396d541ea"
  _type = "arp_core/CannonState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 nbBallsInLeftStock
uint8 nbBallsInRightStock
float64 leftStockerPosition
float64 rightStockerPosition
float64 leftFingerPosition
float64 rightFingerPosition
"""
  __slots__ = ['nbBallsInLeftStock','nbBallsInRightStock','leftStockerPosition','rightStockerPosition','leftFingerPosition','rightFingerPosition']
  _slot_types = ['uint8','uint8','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       nbBallsInLeftStock,nbBallsInRightStock,leftStockerPosition,rightStockerPosition,leftFingerPosition,rightFingerPosition
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(CannonState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nbBallsInLeftStock is None:
        self.nbBallsInLeftStock = 0
      if self.nbBallsInRightStock is None:
        self.nbBallsInRightStock = 0
      if self.leftStockerPosition is None:
        self.leftStockerPosition = 0.
      if self.rightStockerPosition is None:
        self.rightStockerPosition = 0.
      if self.leftFingerPosition is None:
        self.leftFingerPosition = 0.
      if self.rightFingerPosition is None:
        self.rightFingerPosition = 0.
    else:
      self.nbBallsInLeftStock = 0
      self.nbBallsInRightStock = 0
      self.leftStockerPosition = 0.
      self.rightStockerPosition = 0.
      self.leftFingerPosition = 0.
      self.rightFingerPosition = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2B4d.pack(_x.nbBallsInLeftStock, _x.nbBallsInRightStock, _x.leftStockerPosition, _x.rightStockerPosition, _x.leftFingerPosition, _x.rightFingerPosition))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.nbBallsInLeftStock, _x.nbBallsInRightStock, _x.leftStockerPosition, _x.rightStockerPosition, _x.leftFingerPosition, _x.rightFingerPosition,) = _struct_2B4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2B4d.pack(_x.nbBallsInLeftStock, _x.nbBallsInRightStock, _x.leftStockerPosition, _x.rightStockerPosition, _x.leftFingerPosition, _x.rightFingerPosition))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.nbBallsInLeftStock, _x.nbBallsInRightStock, _x.leftStockerPosition, _x.rightStockerPosition, _x.leftFingerPosition, _x.rightFingerPosition,) = _struct_2B4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2B4d = struct.Struct("<2B4d")
