"""autogenerated by genmsg_py from OmniCommand.msg. Do not edit."""
import roslib.message
import struct


class OmniCommand(roslib.message.Message):
  _md5sum = "e1e969d13a87e9761761da894847f23d"
  _type = "arp_core/OmniCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 v_left_driving
float64 v_right_driving
float64 v_rear_driving
float64 p_left_steering
float64 p_right_steering
float64 p_rear_steering
"""
  __slots__ = ['v_left_driving','v_right_driving','v_rear_driving','p_left_steering','p_right_steering','p_rear_steering']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       v_left_driving,v_right_driving,v_rear_driving,p_left_steering,p_right_steering,p_rear_steering
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(OmniCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.v_left_driving is None:
        self.v_left_driving = 0.
      if self.v_right_driving is None:
        self.v_right_driving = 0.
      if self.v_rear_driving is None:
        self.v_rear_driving = 0.
      if self.p_left_steering is None:
        self.p_left_steering = 0.
      if self.p_right_steering is None:
        self.p_right_steering = 0.
      if self.p_rear_steering is None:
        self.p_rear_steering = 0.
    else:
      self.v_left_driving = 0.
      self.v_right_driving = 0.
      self.v_rear_driving = 0.
      self.p_left_steering = 0.
      self.p_right_steering = 0.
      self.p_rear_steering = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.v_left_driving, _x.v_right_driving, _x.v_rear_driving, _x.p_left_steering, _x.p_right_steering, _x.p_rear_steering))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.v_left_driving, _x.v_right_driving, _x.v_rear_driving, _x.p_left_steering, _x.p_right_steering, _x.p_rear_steering,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.v_left_driving, _x.v_right_driving, _x.v_rear_driving, _x.p_left_steering, _x.p_right_steering, _x.p_rear_steering))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.v_left_driving, _x.v_right_driving, _x.v_rear_driving, _x.p_left_steering, _x.p_right_steering, _x.p_rear_steering,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6d = struct.Struct("<6d")
