"""autogenerated by genmsg_py from OmniOdo.msg. Do not edit."""
import roslib.message
import struct


class OmniOdo(roslib.message.Message):
  _md5sum = "d95d1ff231604ee8121ba271496f8a63"
  _type = "arp_core/OmniOdo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 odo_left_driving
float64 odo_right_driving
float64 odo_rear_driving
float64 odo_left_steering
float64 odo_right_steering
float64 odo_rear_steering
float64 time

"""
  __slots__ = ['odo_left_driving','odo_right_driving','odo_rear_driving','odo_left_steering','odo_right_steering','odo_rear_steering','time']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       odo_left_driving,odo_right_driving,odo_rear_driving,odo_left_steering,odo_right_steering,odo_rear_steering,time
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(OmniOdo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.odo_left_driving is None:
        self.odo_left_driving = 0.
      if self.odo_right_driving is None:
        self.odo_right_driving = 0.
      if self.odo_rear_driving is None:
        self.odo_rear_driving = 0.
      if self.odo_left_steering is None:
        self.odo_left_steering = 0.
      if self.odo_right_steering is None:
        self.odo_right_steering = 0.
      if self.odo_rear_steering is None:
        self.odo_rear_steering = 0.
      if self.time is None:
        self.time = 0.
    else:
      self.odo_left_driving = 0.
      self.odo_right_driving = 0.
      self.odo_rear_driving = 0.
      self.odo_left_steering = 0.
      self.odo_right_steering = 0.
      self.odo_rear_steering = 0.
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.odo_left_driving, _x.odo_right_driving, _x.odo_rear_driving, _x.odo_left_steering, _x.odo_right_steering, _x.odo_rear_steering, _x.time))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.odo_left_driving, _x.odo_right_driving, _x.odo_rear_driving, _x.odo_left_steering, _x.odo_right_steering, _x.odo_rear_steering, _x.time,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.odo_left_driving, _x.odo_right_driving, _x.odo_rear_driving, _x.odo_left_steering, _x.odo_right_steering, _x.odo_rear_steering, _x.time))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.odo_left_driving, _x.odo_right_driving, _x.odo_rear_driving, _x.odo_left_steering, _x.odo_right_steering, _x.odo_rear_steering, _x.time,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_7d = struct.Struct("<7d")
