"""autogenerated by genmsg_py from Pose.msg. Do not edit."""
import roslib.message
import struct


class Pose(roslib.message.Message):
  _md5sum = "8c25797b8ddb31a9169f0120ce2255b8"
  _type = "arp_core/Pose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 theta

float64 vx
float64 vy
float64 vtheta

float64 date
"""
  __slots__ = ['x','y','theta','vx','vy','vtheta','date']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       x,y,theta,vx,vy,vtheta,date
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Pose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.theta is None:
        self.theta = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vtheta is None:
        self.vtheta = 0.
      if self.date is None:
        self.date = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.theta = 0.
      self.vx = 0.
      self.vy = 0.
      self.vtheta = 0.
      self.date = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.x, _x.y, _x.theta, _x.vx, _x.vy, _x.vtheta, _x.date))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x, _x.y, _x.theta, _x.vx, _x.vy, _x.vtheta, _x.date,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_7d.pack(_x.x, _x.y, _x.theta, _x.vx, _x.vy, _x.vtheta, _x.date))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x, _x.y, _x.theta, _x.vx, _x.vy, _x.vtheta, _x.date,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_7d = struct.Struct("<7d")
