/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/DifferentialCommand.msg */
#ifndef ARP_CORE_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H
#define ARP_CORE_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_core/DifferentialCommand.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_core::DifferentialCommand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("v_left",m.v_left);
    a & make_nvp("v_right",m.v_right);
}

} // namespace serialization
} // namespace boost

#endif // ARP_CORE_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H

