/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/Obstacle.msg */
#ifndef ARP_CORE_BOOST_SERIALIZATION_OBSTACLE_H
#define ARP_CORE_BOOST_SERIALIZATION_OBSTACLE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_core/Obstacle.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_core::Obstacle_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("detected",m.detected);
}

} // namespace serialization
} // namespace boost

#endif // ARP_CORE_BOOST_SERIALIZATION_OBSTACLE_H

