/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/OmniOdo.msg */
#ifndef ARP_CORE_BOOST_SERIALIZATION_OMNIODO_H
#define ARP_CORE_BOOST_SERIALIZATION_OMNIODO_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_core/OmniOdo.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_core::OmniOdo_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("odo_left_driving",m.odo_left_driving);
    a & make_nvp("odo_right_driving",m.odo_right_driving);
    a & make_nvp("odo_rear_driving",m.odo_rear_driving);
    a & make_nvp("odo_left_steering",m.odo_left_steering);
    a & make_nvp("odo_right_steering",m.odo_right_steering);
    a & make_nvp("odo_rear_steering",m.odo_rear_steering);
    a & make_nvp("time",m.time);
}

} // namespace serialization
} // namespace boost

#endif // ARP_CORE_BOOST_SERIALIZATION_OMNIODO_H

