
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVEA_H
#define TESTSLAVEA_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlaveA_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlaveA_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlaveA_Data;
extern UNS8 SlaveAMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 SlaveAMap2;		/* Mapped at index 0x2001, subindex 0x00*/

#endif // TESTSLAVEA_H
