/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/OrderActionGoal.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONGOAL_H
#define ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONGOAL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/OrderActionGoal.h>
#include <std_msgs/Header.h>
#include "actionlib_msgs/boost/GoalID.h"
#include "arp_master/boost/OrderGoal.h"

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::OrderActionGoal_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("goal_id",m.goal_id);
    a & make_nvp("goal",m.goal);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONGOAL_H

