/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/OrderFeedback.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_ORDERFEEDBACK_H
#define ARP_MASTER_BOOST_SERIALIZATION_ORDERFEEDBACK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/OrderFeedback.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::OrderFeedback_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x_current",m.x_current);
    a & make_nvp("y_current",m.y_current);
    a & make_nvp("theta_current",m.theta_current);
    a & make_nvp("lin_vel",m.lin_vel);
    a & make_nvp("ang_vel",m.ang_vel);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_ORDERFEEDBACK_H

