/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/Start.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_START_H
#define ARP_MASTER_BOOST_SERIALIZATION_START_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/Start.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::Start_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("go",m.go);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_START_H

