CanFestival: Process Data Object (PDO)
Process Data Object (PDO)
[Communication Objects]
Functions
UNS8 sendPDOrequest (CO_Data *d, UNS16 RPDOIndex)
Transmit a PDO request frame on the network to the slave.
UNS8 _sendPDOevent (CO_Data *d, UNS8 isSyncEvent)
Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
void PDOEventTimerAlarm (CO_Data *d, UNS32 pdoNum)
Set timer for PDO event.
void PDOInhibitTimerAlarm (CO_Data *d, UNS32 pdoNum)
Inhibit timer for PDO event.
Detailed Description
PDO is a communication object defined by the DPO communication parameter and PDA mapping parameter objects. It is an uncomfirmed communication service without protocol overhead.
Function Documentation
UNS8 _sendPDOevent (CO_Data * d, UNS8 isSyncEvent)
Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
Parameters:
*d Pointer on a CAN object data structure
isSyncEvent
d
isSyncEvent
Returns:
Definition at line 616 of file pdo.c.
References buildPDO().
Referenced by PDOInit(), and sendPDOevent().
void PDOEventTimerAlarm (CO_Data * d, UNS32 pdoNum)
Set timer for PDO event.
Parameters:
*d Pointer on a CAN object data structure
pdoNum The PDO number
Definition at line 587 of file pdo.c.
References Message::cob_id.
Referenced by proceedPDO(), and TPDO_Communication_Parameter_Callback().
void PDOInhibitTimerAlarm (CO_Data * d, UNS32 pdoNum)
Inhibit timer for PDO event.
Parameters:
*d Pointer on a CAN object data structure
pdoNum The PDO number
Definition at line 597 of file pdo.c.
UNS8 sendPDOrequest (CO_Data * d, UNS16 RPDOIndex)
Transmit a PDO request frame on the network to the slave.
Parameters:
*d Pointer on a CAN object data structure
RPDOIndex Index of the receive PDO
Returns:
CanFestival file descriptor is returned upon success.
0xFF is returned if RPDO Index is not found.
0xFF if error, other in success.
Parameters:
d
cobId
Returns:
Definition at line 121 of file pdo.c.
References Message::cob_id, Message::len, and Message::rtr.