/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/DifferentialCommand.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H
#define ARP_MASTER_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/DifferentialCommand.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::DifferentialCommand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("v_left",m.v_left);
    a & make_nvp("v_right",m.v_right);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_DIFFERENTIALCOMMAND_H

