/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/OrderGoal.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_ORDERGOAL_H
#define ARP_MASTER_BOOST_SERIALIZATION_ORDERGOAL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/OrderGoal.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::OrderGoal_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("type",m.type);
    a & make_nvp("x_des",m.x_des);
    a & make_nvp("y_des",m.y_des);
    a & make_nvp("theta_des",m.theta_des);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_ORDERGOAL_H

