/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/OrderActionFeedback.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONFEEDBACK_H
#define ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONFEEDBACK_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/OrderActionFeedback.h>
#include <std_msgs/Header.h>
#include "actionlib_msgs/boost/GoalStatus.h"
#include "arp_master/boost/OrderFeedback.h"

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::OrderActionFeedback_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("status",m.status);
    a & make_nvp("feedback",m.feedback);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_ORDERACTIONFEEDBACK_H

