/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/OrderAction.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_ORDERACTION_H
#define ARP_MASTER_BOOST_SERIALIZATION_ORDERACTION_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/OrderAction.h>
#include "arp_master/boost/OrderActionGoal.h"
#include "arp_master/boost/OrderActionResult.h"
#include "arp_master/boost/OrderActionFeedback.h"

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::OrderAction_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("action_goal",m.action_goal);
    a & make_nvp("action_result",m.action_result);
    a & make_nvp("action_feedback",m.action_feedback);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_ORDERACTION_H

