/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_master/msg/Pose.msg */
#ifndef ARP_MASTER_BOOST_SERIALIZATION_POSE_H
#define ARP_MASTER_BOOST_SERIALIZATION_POSE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <arp_master/Pose.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::arp_master::Pose_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x",m.x);
    a & make_nvp("y",m.y);
    a & make_nvp("theta",m.theta);
    a & make_nvp("linear_velocity",m.linear_velocity);
    a & make_nvp("angular_velocity",m.angular_velocity);
}

} // namespace serialization
} // namespace boost

#endif // ARP_MASTER_BOOST_SERIALIZATION_POSE_H

