/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/DifferentialCommand.msg */
#ifndef ARP_CORE_MESSAGE_DIFFERENTIALCOMMAND_H
#define ARP_CORE_MESSAGE_DIFFERENTIALCOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace arp_core
{
template <class ContainerAllocator>
struct DifferentialCommand_ : public ros::Message
{
  typedef DifferentialCommand_<ContainerAllocator> Type;

  DifferentialCommand_()
  : v_left(0.0)
  , v_right(0.0)
  {
  }

  DifferentialCommand_(const ContainerAllocator& _alloc)
  : v_left(0.0)
  , v_right(0.0)
  {
  }

  typedef double _v_left_type;
  double v_left;

  typedef double _v_right_type;
  double v_right;


private:
  static const char* __s_getDataType_() { return "arp_core/DifferentialCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "50fa646698267f553e03f81238667677"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 v_left\n\
float64 v_right\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, v_left);
    ros::serialization::serialize(stream, v_right);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, v_left);
    ros::serialization::deserialize(stream, v_right);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(v_left);
    size += ros::serialization::serializationLength(v_right);
    return size;
  }

  typedef boost::shared_ptr< ::arp_core::DifferentialCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arp_core::DifferentialCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct DifferentialCommand
typedef  ::arp_core::DifferentialCommand_<std::allocator<void> > DifferentialCommand;

typedef boost::shared_ptr< ::arp_core::DifferentialCommand> DifferentialCommandPtr;
typedef boost::shared_ptr< ::arp_core::DifferentialCommand const> DifferentialCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arp_core::DifferentialCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arp_core::DifferentialCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arp_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::arp_core::DifferentialCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "50fa646698267f553e03f81238667677";
  }

  static const char* value(const  ::arp_core::DifferentialCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x50fa646698267f55ULL;
  static const uint64_t static_value2 = 0x3e03f81238667677ULL;
};

template<class ContainerAllocator>
struct DataType< ::arp_core::DifferentialCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arp_core/DifferentialCommand";
  }

  static const char* value(const  ::arp_core::DifferentialCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arp_core::DifferentialCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 v_left\n\
float64 v_right\n\
\n\
";
  }

  static const char* value(const  ::arp_core::DifferentialCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arp_core::DifferentialCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arp_core::DifferentialCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.v_left);
    stream.next(m.v_right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DifferentialCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arp_core::DifferentialCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arp_core::DifferentialCommand_<ContainerAllocator> & v) 
  {
    s << indent << "v_left: ";
    Printer<double>::stream(s, indent + "  ", v.v_left);
    s << indent << "v_right: ";
    Printer<double>::stream(s, indent + "  ", v.v_right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARP_CORE_MESSAGE_DIFFERENTIALCOMMAND_H

