/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/Obstacle.msg */
#ifndef ARP_CORE_MESSAGE_OBSTACLE_H
#define ARP_CORE_MESSAGE_OBSTACLE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace arp_core
{
template <class ContainerAllocator>
struct Obstacle_ : public ros::Message
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
  : detected(0.0)
  {
  }

  Obstacle_(const ContainerAllocator& _alloc)
  : detected(0.0)
  {
  }

  typedef float _detected_type;
  float detected;


private:
  static const char* __s_getDataType_() { return "arp_core/Obstacle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "473220c2a67ba4254c1f505aacbafe5e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 detected\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, detected);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, detected);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(detected);
    return size;
  }

  typedef boost::shared_ptr< ::arp_core::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arp_core::Obstacle_<ContainerAllocator>  const> ConstPtr;
}; // struct Obstacle
typedef  ::arp_core::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::arp_core::Obstacle> ObstaclePtr;
typedef boost::shared_ptr< ::arp_core::Obstacle const> ObstacleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arp_core::Obstacle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arp_core::Obstacle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arp_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::arp_core::Obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "473220c2a67ba4254c1f505aacbafe5e";
  }

  static const char* value(const  ::arp_core::Obstacle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x473220c2a67ba425ULL;
  static const uint64_t static_value2 = 0x4c1f505aacbafe5eULL;
};

template<class ContainerAllocator>
struct DataType< ::arp_core::Obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arp_core/Obstacle";
  }

  static const char* value(const  ::arp_core::Obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arp_core::Obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 detected\n\
\n\
";
  }

  static const char* value(const  ::arp_core::Obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arp_core::Obstacle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arp_core::Obstacle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.detected);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Obstacle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arp_core::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arp_core::Obstacle_<ContainerAllocator> & v) 
  {
    s << indent << "detected: ";
    Printer<float>::stream(s, indent + "  ", v.detected);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARP_CORE_MESSAGE_OBSTACLE_H

