/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/Start.msg */
#ifndef ARP_CORE_MESSAGE_START_H
#define ARP_CORE_MESSAGE_START_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace arp_core
{
template <class ContainerAllocator>
struct Start_ : public ros::Message
{
  typedef Start_<ContainerAllocator> Type;

  Start_()
  : go(0)
  {
  }

  Start_(const ContainerAllocator& _alloc)
  : go(0)
  {
  }

  typedef uint8_t _go_type;
  uint8_t go;


private:
  static const char* __s_getDataType_() { return "arp_core/Start"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cde602380b04a9f9d04072dff04b244b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 go\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, go);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, go);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(go);
    return size;
  }

  typedef boost::shared_ptr< ::arp_core::Start_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arp_core::Start_<ContainerAllocator>  const> ConstPtr;
}; // struct Start
typedef  ::arp_core::Start_<std::allocator<void> > Start;

typedef boost::shared_ptr< ::arp_core::Start> StartPtr;
typedef boost::shared_ptr< ::arp_core::Start const> StartConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arp_core::Start_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arp_core::Start_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arp_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::arp_core::Start_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cde602380b04a9f9d04072dff04b244b";
  }

  static const char* value(const  ::arp_core::Start_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcde602380b04a9f9ULL;
  static const uint64_t static_value2 = 0xd04072dff04b244bULL;
};

template<class ContainerAllocator>
struct DataType< ::arp_core::Start_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arp_core/Start";
  }

  static const char* value(const  ::arp_core::Start_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arp_core::Start_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 go\n\
\n\
";
  }

  static const char* value(const  ::arp_core::Start_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arp_core::Start_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arp_core::Start_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.go);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Start_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arp_core::Start_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arp_core::Start_<ContainerAllocator> & v) 
  {
    s << indent << "go: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.go);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARP_CORE_MESSAGE_START_H

