/* Auto-generated by genmsg_cpp for file /opt/ros/ard/arp_core/msg/Velocity.msg */
#ifndef ARP_CORE_MESSAGE_VELOCITY_H
#define ARP_CORE_MESSAGE_VELOCITY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace arp_core
{
template <class ContainerAllocator>
struct Velocity_ : public ros::Message
{
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  Velocity_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef double _linear_type;
  double linear;

  typedef double _angular_type;
  double angular;


private:
  static const char* __s_getDataType_() { return "arp_core/Velocity"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "144a16e4d6b53a0dbadc2e617460a173"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 linear\n\
float64 angular\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, linear);
    ros::serialization::serialize(stream, angular);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, linear);
    ros::serialization::deserialize(stream, angular);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(linear);
    size += ros::serialization::serializationLength(angular);
    return size;
  }

  typedef boost::shared_ptr< ::arp_core::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arp_core::Velocity_<ContainerAllocator>  const> ConstPtr;
}; // struct Velocity
typedef  ::arp_core::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::arp_core::Velocity> VelocityPtr;
typedef boost::shared_ptr< ::arp_core::Velocity const> VelocityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arp_core::Velocity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arp_core::Velocity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arp_core

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::arp_core::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const  ::arp_core::Velocity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x144a16e4d6b53a0dULL;
  static const uint64_t static_value2 = 0xbadc2e617460a173ULL;
};

template<class ContainerAllocator>
struct DataType< ::arp_core::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arp_core/Velocity";
  }

  static const char* value(const  ::arp_core::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arp_core::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 linear\n\
float64 angular\n\
\n\
";
  }

  static const char* value(const  ::arp_core::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arp_core::Velocity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arp_core::Velocity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Velocity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arp_core::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arp_core::Velocity_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<double>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<double>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARP_CORE_MESSAGE_VELOCITY_H

